### ISSUE TITLE
App crashes when clicking "Members List" the first time.

### ISSUE THREAD

**Issue by friedger** [matrix-org/matrix-android-sdk#1]
The first time, when I click on the action bar button "Members list" with the members icon of a room that I entered the first time I get a crash: 

 Process: org.matrix.matrixandroidsdk, PID: 943
    java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
            at org.matrix.androidsdk.rest.model.User.getRealLastActiveAgo(User.java:84)
            at org.matrix.matrixandroidsdk.adapters.RoomMembersAdapter$2.compare(RoomMembersAdapter.java:87)
            at org.matrix.matrixandroidsdk.adapters.RoomMembersAdapter$2.compare(RoomMembersAdapter.java:68)
            at java.util.TimSort.countRunAndMakeAscending(TimSort.java:320)
            at java.util.TimSort.sort(TimSort.java:199)
            at java.util.TimSort.sort(TimSort.java:169)
            at java.util.Arrays.sort(Arrays.java:2010)
            at java.util.Collections.sort(Collections.java:1883)
            at android.widget.ArrayAdapter.sort(ArrayAdapter.java:275)
            at org.matrix.matrixandroidsdk.adapters.RoomMembersAdapter.sortMembers(RoomMembersAdapter.java:119)
            at org.matrix.matrixandroidsdk.fragments.RoomMembersDialogFragment.onCreateView(RoomMembersDialogFragment.java:125)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by joachimre** [comment]
Couldn't reproduce but added null checks which should fix this
https://github.com/matrix-org/matrix-android-sdk/commit/b28db3bc

**Comment by joachimre** [comment]
Managed to reproduce after all. The commit does fix it.

**Comment by Kegsay** [comment]
Closing old issue.
