### ISSUE TITLE
new MXSession always returns NullPointerException

### ISSUE THREAD

**Issue by JhetoX** [matrix-org/matrix-android-sdk#122]
MXSession session = new MXSession(api.getConfig(), handler, getApplicationContext());

java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.matrix.androidsdk.rest.model.login.Credentials.userId' on a null object reference

at org.matrix.androidsdk.util.BingRulesManager.<init>(BingRulesManager.java:99)
                      at org.matrix.androidsdk.MXSession.<init>(MXSession.java:250)
                      at com.jhetox.matrix.client.MainActivity$1.onSuccess(MainActivity.java:45)
                      at com.jhetox.matrix.client.MainActivity$1.onSuccess(MainActivity.java:40)
                      at org.matrix.androidsdk.rest.client.LoginRestClient$6.success(LoginRestClient.java:151)
                      at org.matrix.androidsdk.rest.client.LoginRestClient$6.success(LoginRestClient.java:146)
                      at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
                      at android.os.Handler.handleCallback(Handler.java:746)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5443)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by ylecollen** [comment]
see how to use it.

https://github.com/vector-im/riot-android/blob/master/vector/src/main/java/im/vector/Matrix.java#L574
