### ISSUE TITLE
Crash when reading from timeline

### ISSUE THREAD

**Issue by hannojg** [matrix-org/matrix-android-sdk#565]
**Describe the bug**
We just received a sentry crash report which points to the matrix SDK. Our app uses the react-native matrix SDK, thus we can't exactly pin down what caused the crash (we lose the information between the JS side and the native side in the crash reports). All I can provide is the crash report. I hope it helps.

**To Reproduce**
not applicable 

**Expected behavior**

**Crash report**
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.get(ArrayList.java:437)
    at org.matrix.androidsdk.data.timeline.MXEventTimeline.manageBackEvents(MXEventTimeline.java:420)
    at org.matrix.androidsdk.data.timeline.MXEventTimeline.access$100(MXEventTimeline.java:51)
    at org.matrix.androidsdk.data.timeline.MXEventTimeline$1.onPostExecute(MXEventTimeline.java:552)
    at org.matrix.androidsdk.data.timeline.MXEventTimeline$1.onPostExecute(MXEventTimeline.java:542)
    at android.os.AsyncTask.finish(AsyncTask.java:755)
    at android.os.AsyncTask.access$900(AsyncTask.java:192)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7397)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Smartphone (please complete the following information):**

Architecture | arm64-v8a
-- | --
Architectures | [arm64-v8a, armeabi-v7a, armeabi]
Battery Level | 6%
Brand | Xiaomi
Connection Type | wifi
External Free Storage | 60.0 GB
External Storage Size | 60.0 GB
Free Memory | 853.8 MB
Free Storage | 50.5 GB
Low Memory | False
Manufacturer | Xiaomi
Memory Size | 3.5 GB
Model | Mi A3 (QKQ1.190910.002)

**Additional context**
Using the latest version of the SDK

**Comment by hannojg** [comment]
is that something you expect not happen with the new SDK?
